project:
  type: website

website:
  title: "blog"
  google-analytics: "G-X9HYS83D1C"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/illak
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: journal
    css: styles.css

editor: visual

